public class Constants {
	//Campaigns
	public static final String RECORD_TYPE_VOLUNTEER_CAMPAIGN = 'Volunteer Campaign';
	
	//CustomSettings
	public static final String MONGO_SETTINGS_NAME = 'MongoSettings';
	
	//Common Object Fields
	public static final String MONGO_ID_FIELD_NAME = 'MongoId__c';
	
	//API
	public static final String CONTENT_TYPE_JSON = 'application/json';
	
	//Mongo API
	public static final String MONGO_RESPONSE_SUCCESS_STATUS = 'OK';
	
	//exception messages
	public static final String CALLOUT_CONTENT_NULL = 'The content cannot be null or empty';
	public static final String CALLOUT_PATH_NULL = 'The path parameter cannot be null or empty';
	
}
